# Generated by Django 4.0.1 on 2022-02-27 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apytool', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discrepancie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.EmailField(max_length=254)),
                ('Issues', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='shrimpdata',
            name='species',
            field=models.CharField(choices=[('Tiger Shrimp', 'Tiger Shrimp'), ('L. Vannamei', 'L. Vannamei')], max_length=30),
        ),
    ]
